language: node_js
# nodejs版本
node_js:
  - '10'

# Travis-CI Caching
cache:
  directories:
    - node_modules

# Start: Build Lifecycle
install:
  - yarn

before_script:

script:
  - yarn run build:story 

after_script:
  - cd ./.out
  - echo 'pluto.smallpig.cn' > CNAME
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "feat:travis-ci auto build"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# End: Build LifeCycle

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    
env:
  global: